services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dosecerta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/esquema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/test_insercoes.sql:/docker-entrypoint-initdb.d/02_insert.sql

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: dosecerta
    # Removido o volume para não apagar node_modules
    # volumes:
    #   - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
